"""CODESYS export (IR -> CODESYS .exp text).

CODESYS uses standard IEC ST; the distinguishing markers are the CODESYS export
pragma header and POU framing. The statement body reuses the generic ST renderer.
"""
from __future__ import annotations
from ... import ir
from ...registry import register_backend
from ..st import _stmts

_SCOPE_KW = {ir.VarScope.INPUT: "VAR_INPUT", ir.VarScope.OUTPUT: "VAR_OUTPUT",
             ir.VarScope.LOCAL: "VAR"}


def emit_codesys(program: ir.Program) -> str:
    lines = ["(* @NESTEDCOMMENTS := 'Yes' *)",
             "(* Generated by plcpy - CODESYS export *)",
             f"PROGRAM {program.name}"]
    for scope in (ir.VarScope.INPUT, ir.VarScope.OUTPUT, ir.VarScope.LOCAL):
        decls = [v for v in program.vars if v.scope is scope]
        if not decls:
            continue
        lines.append(_SCOPE_KW[scope])
        for v in decls:
            lines.append(f"    {v.name} : {v.type.value};")
        lines.append("END_VAR")
    lines.extend(_stmts(program.body, 1))
    lines.append("END_PROGRAM")
    return "\n".join(lines) + "\n"


register_backend("codesys", emit_codesys)
