"""Siemens TIA Portal SCL export (IR -> SCL).

SCL is Siemens' Structured Control Language — close to IEC ST but with its own
type names (Bool/Int/Real), FUNCTION_BLOCK framing, and a BEGIN section. The
statement body reuses the generic ST renderer, which is syntactically valid SCL.
"""
from __future__ import annotations
from ... import ir
from ...registry import register_backend
from ..st import _stmts

_SCL_TYPE = {ir.DataType.BOOL: "Bool", ir.DataType.INT: "Int", ir.DataType.REAL: "Real"}
_SCOPE_KW = {ir.VarScope.INPUT: "VAR_INPUT", ir.VarScope.OUTPUT: "VAR_OUTPUT",
             ir.VarScope.LOCAL: "VAR"}


def emit_scl(program: ir.Program) -> str:
    lines = ["// Generated by plcpy - Siemens SCL (TIA Portal) export",
             f'FUNCTION_BLOCK "{program.name}"']
    for scope in (ir.VarScope.INPUT, ir.VarScope.OUTPUT, ir.VarScope.LOCAL):
        decls = [v for v in program.vars if v.scope is scope]
        if not decls:
            continue
        lines.append(_SCOPE_KW[scope])
        for v in decls:
            lines.append(f"    {v.name} : {_SCL_TYPE[v.type]};")
        lines.append("END_VAR")
    lines.append("BEGIN")
    lines.extend(_stmts(program.body, 1))
    lines.append("END_FUNCTION_BLOCK")
    return "\n".join(lines) + "\n"


register_backend("scl", emit_scl)
